project_name: 'SatelliteClassifier'
experiment_name: 'resnet18_pure1'
num_classes: 17
n_epochs: 20
accelerator: 'gpu'
device: 0
monitor_metric: 'val_f1'
monitor_mode: 'max'
threshold: 0.2
metrics_average: 'macro'
freeze_grad: false

model_kwargs:
  model_name: 'resnet18'
  pretrained: true

optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 1e-3
  weight_decay: 1e-5

scheduler: 'torch.optim.lr_scheduler.CosineAnnealingLR'
scheduler_kwargs:
  T_max: 10
  eta_min: 1e-5

losses:
  - name: 'bce'
    weight: 1.0
    loss_fn: 'torch.nn.BCEWithLogitsLoss'
    loss_kwargs: {}

data_config:
  data_path: './data'
  batch_size: 128
  n_workers: 4
  train_size: 0.8
  width: 224
  height: 224
